[project]
name = "wagtail2nix"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
 "wagtail>=7.2.1",
]

[project.scripts]
hello = "wagtail2nix:hello"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
